#!/bin/sh
#
#
#	MAKE flash	
#	MAKE monitor (Ctrl+] to quit)
#

#sudo PATH="$PATH:/home/benoit/dvp/esp32env/xtensa-esp32-elf/bin" IDF_PATH="/home/benoit/dvp/esp32env/esp-idf" make $*
export PATH="$PATH:/f/dvp/esp32env/msys32/opt/xtensa-esp32-elf:/f/dvp/esp32env/msys32/mingw32/bin"
export IDF_PATH="/f/dvp/esp32env/esp-idf"
export MSYSTEM="MINGW32"
make -j4 $*
